import React from 'react';
import {
    Tabs,
    Tab,
    Grid,
    Cell,
    Card,
    CardTitle,
    CardActions,
    CardText,
    Button,
} from 'react-mdl';

// Image Imports
import todo from '../assets/projects/2.JPG';
import guess from '../assets/projects/word.png';
import emit from '../assets/projects/splash.png';
import port from '../assets/projects/portfolio.jpg';
import drone from '../assets/projects/tello_UI.JPG';
import clicky from '../assets/projects/clicky.JPG';
import friend from '../assets/projects/friend_finder.JPG';
import c2s from '../assets/projects/s2c.png';
import wordGuess from '../assets/projects/wordguess.jpg';
import liri from '../assets/projects/liri.JPG';
import bamazon from '../assets/projects/bamazon.JPG';
import trainIMG from '../assets/projects/train.JPG';
import triviaIMG from '../assets/projects/trivia.JPG';
import ocpygifIMG from '../assets/projects/occupy.jpg';
import rdtrpzIMG from '../assets/projects/roadtriperzzz.png';

class Projects extends React.Component {
    constructor(props) {
        super(props)
        this.state = { activeTab: 0 };
    }

    toggleCategories() {
        // React Native Tab
        if (this.state.activeTab === 0) {
            return (
                <div className="projects-flexWrap">
                    {/* Emit */}
                    <Card 
                    className="projectCard" 
                    shadow={5} 
                    style={{ width: '512px', margin: 'auto', borderRadius: 15, marginBottom: 20 }} 
                    onClick={ () =>window.open('https://expo.io/@volksrat71/emit','_blank')}>
                        <CardTitle style={{ color: '#000', height: '176px', background: `url(${emit}) center / cover` }}>Emit</CardTitle>
                        <CardText>
                            Written with React Native in a group of 5, this application allows a user to create a profile where they will have access to chatrooms by category, to choose a specific sport topic. In this project, I learned project management, time allocation and effectively communicating as a team. I learned how to create user authentication from scratch, user interface, cutting out features while still creating a functional app, & react native development as a whole.
                        </CardText>
                        <CardActions border>
                            <Button
                                href="https://expo.io/@volksrat71/emit"
                                target="_blank"
                                colored ripple>Website</Button>
                            <Button
                                href="https://github.com/VolksRat71/emit"
                                target="_blank"
                                colored ripple>Github</Button>
                        </CardActions>
                    </Card>
                    {/* Number Guess React Native */}
                    <Card 
                    className="projectCard" 
                    shadow={5} 
                    style={{ width: '512px', margin: 'auto', borderRadius: 15, marginBottom: 20 }} 
                    onClick={ () =>window.open('https://github.com/VolksRat71/Native_Tutorial/tree/master/rn-complete-guide','_blank')}>                        <CardTitle style={{ color: '#000', height: '176px', background: `url(${guess}) center / cover` }}>Number Guess</CardTitle>
                        <CardText>
                            Written with React Native, this appication tells the user to guess a number (1-99) generated by the computer. This helped me understand User Interface within React Native much better.
                        </CardText>
                        <CardActions border>
                            <Button
                                href="https://github.com/VolksRat71/Native_Tutorial/tree/master/rn-complete-guide"
                                target="_blank"
                                colored ripple>Github</Button>
                        </CardActions>
                    </Card>
                    {/* To Do React Native */}
                    <Card 
                    className="projectCard" 
                    shadow={5} 
                    style={{ width: '512px', margin: 'auto', borderRadius: 15, marginBottom: 20 }} 
                    onClick={ () =>window.open('https://github.com/VolksRat71/Native_Tutorial/tree/master/rn-todo-app','_blank')}>
                        <CardTitle style={{ color: '#000', height: '176px', background: `url(${todo}) center / cover` }}>To Do</CardTitle>
                        <CardText>
                            Written with React Native, this application creates a "To Do List" via a modal by passing data between files using React Hooks and creating a unique i.d per "To Do" item. You may delete items on your list with a neat React Native user feedback. This was my first attempt at React Native. I learned how to use React Native syntaxes and expo test environments.
                        </CardText>
                        <CardActions border>
                            <Button
                                href="https://github.com/VolksRat71/Native_Tutorial/tree/master/rn-todo-app"
                                target="_blank"
                                colored ripple>Github</Button>
                        </CardActions>
                    </Card>
                </div>
            )
            // ReactJS Tab
        } else if (this.state.activeTab === 1) {
            return (
                <div className="projects-flexWrap">
                    {/* Clicky Game */}
                    <Card 
                    className="projectCard" 
                    shadow={5} 
                    style={{ width: '512px', margin: 'auto', borderRadius: 15, marginBottom: 20 }} 
                    onClick={ () =>window.open('https://github.com/VolksRat71/clicky_game','_blank')}>
                        <CardTitle style={{ color: '#000', height: '176px', background: `url(${clicky}) center / cover` }}>Clicky Game</CardTitle>
                        <CardText>
                            This application, made with React, is themed after the show "Bob's Burgers". It is a memory game in which you click as many characters as possible per game without repeating the same character. I learned how to build off of the "create-react-app" boiler plate and understand React file structures.
                        </CardText>
                        <CardActions border>
                            <Button
                                href="https://github.com/VolksRat71/clicky_game"
                                target="_blank"
                                colored ripple>Github</Button>
                        </CardActions>
                    </Card>
                    {/* Drone Controller */}
                    <Card 
                    className="projectCard" 
                    shadow={5} 
                    style={{ width: '512px', margin: 'auto', borderRadius: 15, marginBottom: 20 }} 
                    onClick={ () =>window.open('https://github.com/VolksRat71/DJI_drone_controller','_blank')}>
                        <CardTitle style={{ color: '#000', height: '176px', background: `url(${drone}) center / cover` }}>Drone Controller</CardTitle>
                        <CardText>
                            Featuring React frontend, this application is a controller giving you control of a DJI Tello drone via web browser, but that was only at the surface. Eventually, I was able to build in some automation and stunts, I still have much more planned for this project. Keep an eye on its GitHub if you are interested! In this project, I learned data transfering, working with hardware, it honed my Node.js ablities, as well as building an independant project from an idea to a presentation. By far, one of my favorite projects.
                        </CardText>
                        <CardActions border>
                            <Button
                                href="https://github.com/VolksRat71/DJI_drone_controller"
                                target="_blank"
                                colored ripple>Github</Button>
                        </CardActions>
                    </Card>
                    {/* Portfolio */}
                    <Card 
                    className="projectCard" 
                    shadow={5} 
                    style={{ width: '512px', margin: 'auto', borderRadius: 15, marginBottom: 20 }} 
                    onClick={ () =>window.open('https://github.com/VolksRat71/portfolio','_blank')}>
                        <CardTitle style={{ color: '#fff', height: '176px', background: `url(${port}) center / cover` }}>Portfolio</CardTitle>
                        <CardText>
                            The Website you are currently on was written with React. There are tons of functions and features I learned while creating this! If you have any feedback, please refer to my "Resume" or "Contact" options on the side navigation to contact me.
                        </CardText>
                        <CardActions border>
                            <Button
                                href="https://github.com/VolksRat71/portfolio"
                                target="_blank"
                                colored ripple>Github</Button>
                        </CardActions>
                    </Card>
                </div>
            )
            // Full Stack Tab
        } else if (this.state.activeTab === 2) {
            return (
                <div className="projects-flexWrap">
                    {/* Seller2Cellar */}
                    <Card 
                    className="projectCard" 
                    shadow={5} 
                    style={{ width: '512px', margin: 'auto', borderRadius: 15, marginBottom: 20 }} 
                    onClick={ () =>window.open('https://glacial-plains-59439.herokuapp.com','_blank')}>
                        <CardTitle style={{ color: '#fff', height: '176px', background: `url(${c2s}) center / cover` }}>Seller2Cellar</CardTitle>
                        <CardText>
                            This project was completed with a group of 5 including myself. Seller2Cellar is a full stack application allowing the user to catalogue their wine collection and buy/sell with other users. My duties included Frontend and User experience. I learned how to complete a task under extreme pressure, working late into the night with a fellow student. I had finally gotten a taste of deadlines and how it may feel impossible to meet them, but pushing through and being proud of what you accoplished. Even if it wan't considered perfect. 
                        </CardText>
                        <CardActions border>
                            <Button
                                href="https://glacial-plains-59439.herokuapp.com"
                                target="_blank"
                                colored ripple>Website</Button>
                            <Button
                                href="https://github.com/VolksRat71/Cellar2Sellers"
                                target="_blank"
                                colored ripple>Github</Button>
                        </CardActions>
                    </Card>
                    {/* Friend Finder */}
                    <Card 
                    className="projectCard" 
                    shadow={5} 
                    style={{ width: '512px', margin: 'auto', borderRadius: 15, marginBottom: 20 }} 
                    onClick={ () =>window.open('https://fierce-bastion-39629.herokuapp.com/','_blank')}>
                        <CardTitle style={{ color: '#000', height: '176px', background: `url(${friend}) center / cover` }}>Friend Finder</CardTitle>
                        <CardText>
                            Friend Finder is a fullstack application, themed after the show "The Office", which compares personality traits with characters in "The Office" to find the user a friend with similar traits. I learned how to use Express servers and build a full stack appication with a prewritten boilerplate.
                        </CardText>
                        <CardActions border>
                            <Button
                                href="https://fierce-bastion-39629.herokuapp.com/"
                                target="_blank"
                                colored ripple>Website</Button>
                            <Button
                                href="https://github.com/VolksRat71/friend_finder"
                                target="_blank"
                                colored ripple>Github</Button>
                        </CardActions>
                    </Card>
                </div>
            )
            // Backend
        } else if (this.state.activeTab === 3) {
            return (
                <div className="projects-flexWrap">
                    {/* bamazon */}
                    <Card 
                    className="projectCard" 
                    shadow={5} 
                    style={{ width: '512px', margin: 'auto', borderRadius: 15, marginBottom: 20 }} 
                    onClick={ () =>window.open('https://github.com/VolksRat71/bamazon','_blank')}>
                        <CardTitle style={{ color: '#fff', height: '176px', background: `url(${bamazon}) center / cover` }}>Bamazon</CardTitle>
                        <CardText>
                            Written with Node.js, this application is designed to keep track of an inventory database written in mySQL. The user can choose either "customer" or "manager" functions, and the README includes how to use each version. I learned how to access information in a SQL database using only a Node server.
                        </CardText>
                        <CardActions border>
                            <Button
                                href="https://github.com/VolksRat71/bamazon"
                                target="_blank"
                                colored ripple>Github</Button>
                        </CardActions>
                    </Card>
                    {/* Liri */}
                    <Card 
                    className="projectCard" 
                    shadow={5} 
                    style={{ width: '512px', margin: 'auto', borderRadius: 15, marginBottom: 20 }} 
                    onClick={ () =>window.open('https://github.com/VolksRat71/liriNode','_blank')}>
                        <CardTitle style={{ color: '#fff', height: '176px', background: `url(${liri}) center / cover` }}>Liri</CardTitle>
                        <CardText>
                            Written with Node.js, this application sends a request to 1 of 3 different API's that are determined by user input in a CLI (example: node liri concert-this NOFX). Upon API response, it will be formatted and displayed in CLI. I learned how to access API json's using only a Node server.
                        </CardText>
                        <CardActions border>
                            <Button
                                href="https://github.com/VolksRat71/liriNode"
                                target="_blank"
                                colored ripple>Github</Button>
                        </CardActions>
                    </Card>
                    {/* Word Guess */}
                    <Card 
                    className="projectCard" 
                    shadow={5} 
                    style={{ width: '512px', margin: 'auto', borderRadius: 15, marginBottom: 20 }} 
                    onClick={ () =>window.open('https://github.com/VolksRat71/constructorWordGuess','_blank')}>
                        <CardTitle style={{ color: '#fff', height: '176px', background: `url(${wordGuess}) center / cover` }}>Word Guess</CardTitle>
                        <CardText>
                            Written with Node.JS, this application compares user input keys to letters of an iconic car name. Each correct guess will be revealed to user. I learned how to use Node.js in general with this application, it was my first backend project.
                        </CardText>
                        <CardActions border>
                            <Button
                                href="https://github.com/VolksRat71/constructorWordGuess"
                                target="_blank"
                                colored ripple>Github</Button>
                        </CardActions>
                    </Card>
                </div>
            )
            // Frontend Tab
        } else {
            return (
                <div className="projects-flexWrap">
                    {/* RoadTripperZzz */}
                    <Card 
                    className="projectCard" 
                    shadow={5} 
                    style={{ width: '512px', margin: 'auto', borderRadius: 15, marginBottom: 20 }} 
                    onClick={ () =>window.open('https://volksrat71.github.io/project-1/project-1/index.html','_blank')}>
                        <CardTitle style={{ color: '#fff', height: '176px', background: `url(${rdtrpzIMG}) center / cover` }}>RoadtripperZzz</CardTitle>
                        <CardText>
                            This application was built with a group of 4 including myself. It was intended to help the indecisive traveler choose a destination within the Pacific Northwest. My Primary duties included layout and general front-end User Experience. I also built in an obvious easter egg, which I hope you enjoy. In this project, I learned how to build a application as a team memeber rather than independantly. It tought me how to use vanilla javascript logic in a "real-world" setting as well as honeing my Bootstrap and HTML abilities. 
                        </CardText>
                        <CardActions border>
                            <Button
                                href="https://volksrat71.github.io/project-1/project-1/index.html"
                                target="_blank"
                                colored ripple>Website</Button>
                            <Button
                                href="https://github.com/VolksRat71/project-1"
                                target="_blank"
                                colored ripple>Github</Button>
                        </CardActions>
                    </Card>
                    {/* Occupy Gif */}
                    <Card 
                    className="projectCard" 
                    shadow={5} 
                    style={{ width: '512px', margin: 'auto', borderRadius: 15, marginBottom: 20 }} 
                    onClick={ () =>window.open('https://volksrat71.github.io/GifTastic/','_blank')}>
                        <CardTitle style={{ color: '#fff', height: '176px', background: `url(${ocpygifIMG}) center / cover` }}>Occupy GIF</CardTitle>
                        <CardText>
                            A simple frontend application, which was intended to learn requests and responses to an API. I decided to take a step further and flex a little frontend User Experience. I learned how to communicate with an API and modify incomming data, also format it correctly for your needs.
                        </CardText>
                        <CardActions border>
                            <Button
                                href="https://volksrat71.github.io/GifTastic/"
                                target="_blank"
                                colored ripple>Website</Button>
                            <Button
                                href="https://github.com/VolksRat71/GifTastic"
                                target="_blank"
                                colored ripple>Github</Button>
                        </CardActions>
                    </Card>
                    {/* Train Schedueler */}
                    <Card 
                    className="projectCard" 
                    shadow={5} 
                    style={{ width: '512px', margin: 'auto', borderRadius: 15, marginBottom: 20 }} 
                    onClick={ () =>window.open('https://volksrat71.github.io/trainScheduler/','_blank')}>
                        <CardTitle style={{ color: '#fff', height: '176px', background: `url(${trainIMG}) center / cover` }}>Train Scheduler</CardTitle>
                        <CardText>
                            A mostly frontend application that communicates with a Google Firebase. Feel free to add your own trains to the schedule, as I will keep an eye on the database for any changes! I learned how to use a database and dynamically insert into a Bootstrap table.
                        </CardText>
                        <CardActions border>
                            <Button
                                href="https://volksrat71.github.io/trainScheduler/"
                                target="_blank"
                                colored ripple>Website</Button>
                            <Button
                                href="https://github.com/VolksRat71/trainScheduler"
                                target="_blank"
                                colored ripple>Github</Button>
                        </CardActions>
                    </Card>
                    {/* Car Trivia */}
                    <Card 
                    className="projectCard" 
                    shadow={5} 
                    style={{ width: '512px', margin: 'auto', borderRadius: 15, marginBottom: 20 }} 
                    onClick={ () =>window.open('https://volksrat71.github.io/triviaGame/','_blank')}>
                        <CardTitle style={{ color: '#fff', height: '176px', background: `url(${triviaIMG}) center / cover` }}>Car Trivia</CardTitle>
                        <CardText>
                            Written with mostly jQuery logic, this was my first attempt at using timers and populating out of arrays. If you feel up to the challenge, give it a try! 
                        </CardText>
                        <CardActions border>
                            <Button
                                href="https://volksrat71.github.io/triviaGame/"
                                target="_blank"
                                colored ripple>Website</Button>
                            <Button
                                href="https://github.com/VolksRat71/triviaGame"
                                target="_blank"
                                colored ripple>Github</Button>
                        </CardActions>
                    </Card>
                </div>
            )
        }
    }

    render() {
        return (
            <div className="project-tabs">
                <Tabs className="tab-header" activeTab={this.state.activeTab} onChange={(tabId) => this.setState({ activeTab: tabId })} ripple>
                    <Tab>React Native</Tab>
                    <Tab>ReactJS</Tab>
                    <Tab>Full Stack</Tab>
                    <Tab>Backend</Tab>
                    <Tab>Frontend</Tab>
                </Tabs>
                <Grid>
                    <Cell col={12}>
                        <div className="content">
                            {this.toggleCategories()}
                        </div>
                    </Cell>
                </Grid>
            </div>
        );
    }
}

export default Projects;